version: '3'

services:
  aryabhatta:
    build: .
    env_file:
      - .env
    command: bash initiate_app.sh
    volumes:
      - ./migrations:/code/migrations
      - /var/log/sleep:/var/log/sleep
    ports:
      - "10004:8000"

networks:
  default:
    external:
        name: sleep-network


