version: '2.1'
services:
  auth:
    image: registry.gitlab.renewbuy.in/sleep/auth:latest
    env_file:
        - .env
    command: ./initiate_app.sh
    volumes:
      - ./migrations:/code/migrations
    ports:
      - "10012:8000"
networks:
  sleep-network:
  #default:
    external: true
      # name: sleep-network
