"""bank_ref_no added in payment

Revision ID: 0fa820fc5598
Revises: abb04c8ef4bc
Create Date: 2023-04-06 14:45:44.233833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa820fc5598'
down_revision = 'abb04c8ef4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('bank_ref_no', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'bank_ref_no')
    # ### end Alembic commands ###
