"""transaction id in consent

Revision ID: 1cddccca746e
Revises: a0cba80e759f
Create Date: 2023-01-04 19:39:29.439178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cddccca746e'
down_revision = 'a0cba80e759f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('transaction_id', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consent', 'transaction_id')
    # ### end Alembic commands ###
