"""added city_id field in cheque_details table

Revision ID: 27717fa47bd6
Revises: 367cf0a964be
Create Date: 2023-03-23 14:55:37.677620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27717fa47bd6'
down_revision = '367cf0a964be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cheque_details', sa.Column('city_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cheque_details', 'city_id')
    # ### end Alembic commands ###
