"""vb64_certificate_url Field added in vb64Record table

Revision ID: 2d55d65982b7
Revises: 31d20afe0728
Create Date: 2023-05-12 16:32:00.383249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d55d65982b7'
down_revision = '31d20afe0728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vb64record', sa.Column('vb64_certificate_url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vb64record', 'vb64_certificate_url')
    # ### end Alembic commands ###
