"""vb64_record endoresement_no added

Revision ID: 31d20afe0728
Revises: 55d0db426bc0
Create Date: 2023-05-02 13:37:02.315159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d20afe0728'
down_revision = '55d0db426bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vb64record', sa.Column('endorsement_number', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vb64record', 'endorsement_number')
    # ### end Alembic commands ###
