"""order_id added in payment

Revision ID: 367cf0a964be
Revises: a166619ea1df
Create Date: 2023-03-09 16:29:52.707968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367cf0a964be'
down_revision = 'a166619ea1df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('order_id', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'order_id')
    # ### end Alembic commands ###
