"""transction_date added in payment

Revision ID: 55d0db426bc0
Revises: 0fa820fc5598
Create Date: 2023-04-19 13:13:38.980966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d0db426bc0'
down_revision = '0fa820fc5598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('transaction_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'transaction_date')
    # ### end Alembic commands ###
