"""payment reference id created

Revision ID: 7303fc3d1221
Revises: 27717fa47bd6
Create Date: 2023-03-27 18:38:13.845711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7303fc3d1221'
down_revision = '27717fa47bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'amount')
    # ### end Alembic commands ###
