"""added dealer code and dealer name in Cheque_details model

Revision ID: a166619ea1df
Revises: b1f556160b8e
Create Date: 2023-02-16 00:02:50.264029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a166619ea1df'
down_revision = 'b1f556160b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cheque_details', sa.Column('dealer_code', sa.VARCHAR(), nullable=True))
    op.add_column('cheque_details', sa.Column('dealer_name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cheque_details', 'dealer_name')
    op.drop_column('cheque_details', 'dealer_code')
    # ### end Alembic commands ###
