"""payment status added in payment

Revision ID: abb04c8ef4bc
Revises: eb38ef57eed1
Create Date: 2023-04-03 11:58:59.810607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb04c8ef4bc'
down_revision = 'eb38ef57eed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('billing_payment_status_fkey', 'billing', type_='foreignkey')
    op.drop_column('billing', 'payment_status')
    op.add_column('billing', sa.Column('billing_status', sa.Integer(), nullable=True))
    op.create_foreign_key('billing_payment_status_fkey', 'billing', 'payment_status', ['billing_status'], ['id'])
    op.add_column('payment', sa.Column('payment_status', sa.Integer(), nullable=True))
    op.create_foreign_key('payment_payment_status_fkey', 'payment', 'payment_status', ['payment_status'], ['id'])
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_payment_status_fkey', 'payment', type_='foreignkey')
    op.drop_column('payment', 'payment_status')
    op.drop_constraint('billing_payment_status_fkey', 'billing', type_='foreignkey')
    op.drop_column('billing', 'billing_status')
    op.add_column('billing', sa.Column('payment_status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('billing_payment_status_fkey', 'billing', 'payment_status', ['payment_status'], ['id'])
    # ### end Alembic commands ###
