"""dealer_payment_mapping

Revision ID: b1f556160b8e
Revises: 1cf5d211652f
Create Date: 2023-02-06 11:53:55.829027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f556160b8e'
down_revision = '1cf5d211652f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_payment_mapping',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_mode_id', sa.Integer(), nullable=True),
    sa.Column('dealer_code', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['payment_mode_id'], ['payment_mode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dealer_payment_mapping')
    # ### end Alembic commands ###
