"""payment status added in billing

Revision ID: eb38ef57eed1
Revises: 7303fc3d1221
Create Date: 2023-03-31 15:10:57.195381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb38ef57eed1'
down_revision = '7303fc3d1221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('payment_status', sa.Integer(), nullable=True))
    op.create_foreign_key('billing_payment_status_fkey', 'billing', 'payment_status', ['payment_status'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('billing_payment_status_fkey', 'billing', type_='foreignkey')
    op.drop_column('billing', 'payment_status')
    # ### end Alembic commands ###
