"""Added designated_person_code for Onboarding data

Revision ID: 0040afb071a9
Revises: 64196f4e239d
Create Date: 2023-06-28 11:17:27.691639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0040afb071a9'
down_revision = '64196f4e239d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_meta_data', sa.Column('designated_person_code', sa.VARCHAR(), nullable=True))
    op.drop_column('user_meta_data', 'pos_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_meta_data', sa.Column('pos_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_meta_data', 'designated_person_code')
    # ### end Alembic commands ###
