"""Added admin role models for Admin portal

Revision ID: 01dcd361bf58
Revises: 1b2b08ab4282
Create Date: 2023-05-22 12:47:42.010127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01dcd361bf58'
down_revision = '1b2b08ab4282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_role',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_role_group_id'), 'admin_role', ['group_id'], unique=False)
    op.create_table('role_module_permission',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('admin_role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admin_role_id'], ['admin_role.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_module_permission_admin_role_id'), 'role_module_permission', ['admin_role_id'], unique=False)
    op.create_index(op.f('ix_role_module_permission_module_id'), 'role_module_permission', ['module_id'], unique=False)
    op.alter_column('modules', 'module_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'module_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_role_module_permission_module_id'), table_name='role_module_permission')
    op.drop_index(op.f('ix_role_module_permission_admin_role_id'), table_name='role_module_permission')
    op.drop_table('role_module_permission')
    op.drop_index(op.f('ix_admin_role_group_id'), table_name='admin_role')
    op.drop_table('admin_role')
    op.drop_table('group')
    # ### end Alembic commands ###
