"""Updated User model

Revision ID: 0f884ed7c179
Revises: ab295ce44c2d
Create Date: 2023-05-23 16:51:13.752933

"""
from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f884ed7c179'
down_revision = 'ab295ce44c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportee',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('manager_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportee_manager_id'), 'reportee', ['manager_id'], unique=False)
    op.create_index(op.f('ix_reportee_user_id'), 'reportee', ['user_id'], unique=False)
    op.add_column('user', sa.Column('employee_code', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('admin_role_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('region', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('creator_editor_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.create_index(op.f('ix_user_admin_role_id'), 'user', ['admin_role_id'], unique=False)
    op.create_index(op.f('ix_user_creator_editor_id'), 'user', ['creator_editor_id'], unique=False)
    op.create_foreign_key('creator_editor_fkey', 'user', 'user', ['creator_editor_id'], ['id'])
    op.create_foreign_key('admin_role_user_fkey', 'user', 'admin_role', ['admin_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('creator_editor_fkey', 'user', type_='foreignkey')
    op.drop_constraint('admin_role_user_fkey', 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_creator_editor_id'), table_name='user')
    op.drop_index(op.f('ix_user_admin_role_id'), table_name='user')
    op.drop_column('user', 'creator_editor_id')
    op.drop_column('user', 'region')
    op.drop_column('user', 'admin_role_id')
    op.drop_column('user', 'employee_code')
    op.drop_index(op.f('ix_reportee_user_id'), table_name='reportee')
    op.drop_index(op.f('ix_reportee_manager_id'), table_name='reportee')
    op.drop_table('reportee')
    # ### end Alembic commands ###
