"""added pos_code field in user_meta_data

Revision ID: 1b2b08ab4282
Revises: ff306a185d3c
Create Date: 2023-03-17 16:27:13.611790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2b08ab4282'
down_revision = 'ff306a185d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_meta_data', sa.Column('pos_code', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_meta_data', 'pos_code')
    # ### end Alembic commands ###
