"""added group code in module table

Revision ID: 52ca85c3377a
Revises: 7cc9dfd28171
Create Date: 2023-01-19 11:56:53.584792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ca85c3377a'
down_revision = '7cc9dfd28171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('module_code', sa.VARCHAR(), nullable=True))
    op.add_column('modules', sa.Column('group_code', sa.VARCHAR(), nullable=True))
    op.drop_column('modules', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('modules', 'group_code')
    op.drop_column('modules', 'module_code')
    # ### end Alembic commands ###
