"""relationship_manager

Revision ID: 5df11a22d4ca
Revises: d7ed2861b5f2
Create Date: 2023-05-30 15:14:42.593264

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '5df11a22d4ca'
down_revision = 'd7ed2861b5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_manager_user_mapping',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_manager_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['relationship_manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relation_manager_user_mapping_relationship_manager_id'), 'relation_manager_user_mapping', ['relationship_manager_id'], unique=False)
    op.create_index(op.f('ix_relation_manager_user_mapping_user_id'), 'relation_manager_user_mapping', ['user_id'], unique=True)
    op.create_table('role_change_log',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('creator_editor', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['creator_editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_change_log_creator_editor'), 'role_change_log', ['creator_editor'], unique=False)
    op.create_index(op.f('ix_role_change_log_role_id'), 'role_change_log', ['role_id'], unique=False)
    op.create_table('user_change_log',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('creator_editor', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['creator_editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_change_log_creator_editor'), 'user_change_log', ['creator_editor'], unique=False)
    op.create_index(op.f('ix_user_change_log_user_id'), 'user_change_log', ['user_id'], unique=False)
    op.drop_index('ix_reportee_user_id', table_name='reportee')
    op.create_index(op.f('ix_reportee_user_id'), 'reportee', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reportee_user_id'), table_name='reportee')
    op.create_index('ix_reportee_user_id', 'reportee', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_change_log_user_id'), table_name='user_change_log')
    op.drop_index(op.f('ix_user_change_log_creator_editor'), table_name='user_change_log')
    op.drop_table('user_change_log')
    op.drop_index(op.f('ix_role_change_log_role_id'), table_name='role_change_log')
    op.drop_index(op.f('ix_role_change_log_creator_editor'), table_name='role_change_log')
    op.drop_table('role_change_log')
    op.drop_index(op.f('ix_relation_manager_user_mapping_user_id'), table_name='relation_manager_user_mapping')
    op.drop_index(op.f('ix_relation_manager_user_mapping_relationship_manager_id'), table_name='relation_manager_user_mapping')
    op.drop_table('relation_manager_user_mapping')
    # ### end Alembic commands ###
