"""Added dealer_details Model for Onboarding data

Revision ID: 64196f4e239d
Revises: acfa7d71e156
Create Date: 2023-06-23 16:50:44.805020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64196f4e239d'
down_revision = 'acfa7d71e156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_details',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_name', sa.VARCHAR(), nullable=True),
    sa.Column('outlet_code', sa.VARCHAR(), nullable=True),
    sa.Column('primary_address', sa.VARCHAR(), nullable=True),
    sa.Column('outlet_city', sa.VARCHAR(), nullable=True),
    sa.Column('outlet_pincode', sa.VARCHAR(), nullable=True),
    sa.Column('misp_code', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dealer_details')
    # ### end Alembic commands ###
