"""misp_code added in user_meta_data

Revision ID: 91e6e26da37e
Revises: 52ca85c3377a
Create Date: 2023-02-22 12:30:06.929776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e6e26da37e'
down_revision = '52ca85c3377a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_meta_data', sa.Column('misp_code', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_meta_data', 'misp_code')
    # ### end Alembic commands ###
