"""Update Admin role table with create_edit & is_create_edit fields

Revision ID: ab295ce44c2d
Revises: 01dcd361bf58
Create Date: 2023-05-23 12:13:03.842925

"""
from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ab295ce44c2d'
down_revision = '01dcd361bf58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role', sa.Column('creator_editor', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.add_column('admin_role', sa.Column('has_create_update_access', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_admin_role_creator_editor'), 'admin_role', ['creator_editor'], unique=False)
    op.create_foreign_key('admin_role_creator_editor_fkey', 'admin_role', 'user', ['creator_editor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_role_creator_editor_fkey', 'admin_role', type_='foreignkey')
    op.drop_index(op.f('ix_admin_role_creator_editor'), table_name='admin_role')
    op.drop_column('admin_role', 'has_create_update_access')
    op.drop_column('admin_role', 'creator_editor')
    # ### end Alembic commands ###
