"""Added module full name in Module table

Revision ID: aecc3acf6420
Revises: 0040afb071a9
Create Date: 2023-07-04 15:39:43.044440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aecc3acf6420'
down_revision = '0040afb071a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('module_full_name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'module_full_name')
    # ### end Alembic commands ###
