"""Added admin role models for Admin portal

Revision ID: d7ed2861b5f2
Revises: 0f884ed7c179
Create Date: 2023-05-24 13:04:01.503880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7ed2861b5f2'
down_revision = '0f884ed7c179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_creator_editor_id', table_name='user')
    op.drop_constraint('creator_editor_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'creator_editor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('creator_editor_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('creator_editor_fkey', 'user', 'user', ['creator_editor_id'], ['id'])
    op.create_index('ix_user_creator_editor_id', 'user', ['creator_editor_id'], unique=False)
    # ### end Alembic commands ###
