"""misp user mapping table

Revision ID: ff306a185d3c
Revises: 91e6e26da37e
Create Date: 2023-02-22 13:25:28.863870

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'ff306a185d3c'
down_revision = '91e6e26da37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misp_user_mapping',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_code', sa.VARCHAR(), nullable=True),
    sa.Column('misp_code', sa.VARCHAR(), nullable=True),
    sa.Column('misp_user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['misp_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misp_user_mapping_misp_user_id'), 'misp_user_mapping', ['misp_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_misp_user_mapping_misp_user_id'), table_name='misp_user_mapping')
    op.drop_table('misp_user_mapping')
    # ### end Alembic commands ###
