"""initial update

Revision ID: 10b607ebaa02
Revises: 
Create Date: 2023-01-04 22:31:06.485731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b607ebaa02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_slug', sa.VARCHAR(), nullable=False),
    sa.Column('email_template', sa.VARCHAR(), nullable=True),
    sa.Column('is_dlt_approved', sa.Boolean(), nullable=True),
    sa.Column('dlt_template_id', sa.VARCHAR(), nullable=True),
    sa.Column('sms_template', sa.VARCHAR(), nullable=True),
    sa.Column('whatsapp_template', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication_request',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('templates_id', sa.Integer(), nullable=True),
    sa.Column('raw_request', sa.VARCHAR(), nullable=True),
    sa.Column('raw_response', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.Enum('received', 'processing', 'sent', 'error', name='statustype'), nullable=True),
    sa.Column('channel', sa.Enum('whatsapp', 'sms', 'email', name='channeltype'), nullable=True),
    sa.Column('worker_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['templates_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_request')
    op.drop_table('templates')
    # ### end Alembic commands ###
