"""product wise UIN

Revision ID: 13d5e09d61d4
Revises: 95a5f5890bed
Create Date: 2023-04-25 17:12:45.917518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d5e09d61d4'
down_revision = '95a5f5890bed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addon', sa.Column('saod_uin', sa.VARCHAR(), nullable=True))
    op.add_column('addon', sa.Column('satp_uin', sa.VARCHAR(), nullable=True))
    op.add_column('addon', sa.Column('bundle_uin', sa.VARCHAR(), nullable=True))
    op.add_column('addon', sa.Column('comprehensive_uin', sa.VARCHAR(), nullable=True))
    op.drop_constraint('addon_uin_key', 'addon', type_='unique')
    op.create_unique_constraint('addon_comprehensive_uin_uqk', 'addon', ['comprehensive_uin'])
    op.create_unique_constraint('addon_satp_uin_uqk', 'addon', ['satp_uin'])
    op.create_unique_constraint('addon_saod_uin_uqk', 'addon', ['saod_uin'])
    op.create_unique_constraint('addon_bundle_uin_uqk', 'addon', ['bundle_uin'])
    op.drop_column('addon', 'uin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addon', sa.Column('uin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('addon_bundle_uin_uqk', 'addon', type_='unique')
    op.drop_constraint('addon_saod_uin_uqk', 'addon', type_='unique')
    op.drop_constraint('addon_satp_uin_uqk', 'addon', type_='unique')
    op.drop_constraint('addon_comprehensive_uin_uqk', 'addon', type_='unique')
    op.create_unique_constraint('addon_uin_key', 'addon', ['uin'])
    op.drop_column('addon', 'comprehensive_uin')
    op.drop_column('addon', 'bundle_uin')
    op.drop_column('addon', 'satp_uin')
    op.drop_column('addon', 'saod_uin')
    # ### end Alembic commands ###
