"""added inspection_require column in insurer

Revision ID: 266cdb7fb862
Revises: 83888a8d8fb0
Create Date: 2023-03-15 13:14:06.257884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266cdb7fb862'
down_revision = '83888a8d8fb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurer', sa.Column('is_inspection_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurer', 'is_inspection_required')
    # ### end Alembic commands ###
