"""dealer model updated

Revision ID: 372ca06bcba5
Revises: c9ad7416bb5f
Create Date: 2023-01-31 20:04:37.528040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372ca06bcba5'
down_revision = 'c9ad7416bb5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dealer_person_dealer_id_key', 'dealer_person', type_='unique')
    op.drop_constraint('sales_manager_dealer_id_key', 'sales_manager', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sales_manager_dealer_id_key', 'sales_manager', ['dealer_id'])
    op.create_unique_constraint('dealer_person_dealer_id_key', 'dealer_person', ['dealer_id'])
    # ### end Alembic commands ###
