"""added codes for dp and sp

Revision ID: 3e9026e380fd
Revises: c7b1dadf0273
Create Date: 2023-02-22 15:58:53.979639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9026e380fd'
down_revision = 'c7b1dadf0273'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designated_person', sa.Column('code', sa.VARCHAR(), nullable=True))
    op.add_column('sales_manager', sa.Column('code', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_manager', 'code')
    op.drop_column('designated_person', 'code')
    # ### end Alembic commands ###
