"""added foreign key ref. in insurer_vehicle_cover_mapping

Revision ID: 83888a8d8fb0
Revises: b6cb4137c77d
Create Date: 2023-03-14 15:02:45.117499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83888a8d8fb0'
down_revision = 'b6cb4137c77d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurer_vehicle_cover_mapping', sa.Column('policy_type_vehicle_cover_id', sa.Integer(), nullable=True))
    op.drop_constraint('insurer_vehicle_cover_mapping_vehicle_cover_id_fkey', 'insurer_vehicle_cover_mapping', type_='foreignkey')
    op.create_foreign_key(None, 'insurer_vehicle_cover_mapping', 'policy_type_vehicle_cover_mapping', ['policy_type_vehicle_cover_id'], ['id'])
    op.drop_column('insurer_vehicle_cover_mapping', 'vehicle_cover_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurer_vehicle_cover_mapping', sa.Column('vehicle_cover_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'insurer_vehicle_cover_mapping', type_='foreignkey')
    op.create_foreign_key('insurer_vehicle_cover_mapping_vehicle_cover_id_fkey', 'insurer_vehicle_cover_mapping', 'vehicle_cover', ['vehicle_cover_id'], ['id'])
    op.drop_column('insurer_vehicle_cover_mapping', 'policy_type_vehicle_cover_id')
    # ### end Alembic commands ###
