"""feedfile insurer flag

Revision ID: 867e7868f53a
Revises: ad282b65267d
Create Date: 2023-06-06 12:23:27.923790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867e7868f53a'
down_revision = 'ad282b65267d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurer', sa.Column('is_feedfile_requested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurer', 'is_feedfile_requested')
    # ### end Alembic commands ###
