"""added new enum values in od_tp_conditions

Revision ID: 95a5f5890bed
Revises: f2b0d82fc60a
Create Date: 2023-03-23 17:58:39.868980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a5f5890bed'
down_revision = 'f2b0d82fc60a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE ODTPConditions ADD VALUE 'OD_EXPIRY_DIFF_TP_EXPIRY_EQ_ZERO'")
        op.execute("ALTER TYPE ODTPConditions ADD VALUE 'OD_EXPIRY_DIFF_TP_EXPIRY_LT_ZERO'")
        op.execute("ALTER TYPE ODTPConditions ADD VALUE 'OD_EXPIRY_DIFF_TP_EXPIRY_EQ_MINUS_ONE'")
        op.execute("ALTER TYPE ODTPConditions ADD VALUE 'OD_EXPIRY_DIFF_TP_EXPIRY_LT_MINUS_ONE'")
        op.execute("ALTER TYPE CurrentDateConditions ADD VALUE 'CURRENT_DATE_LT_OD_EXPIRY_AND_TP_EXPIRY'")
        op.execute("ALTER TYPE CurrentDateConditions ADD VALUE 'CURRENT_DATE_LT_TP_EXPIRY_AND_GT_OD_EXPIRY'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE ODTPConditions AS ENUM('OD_EXPIRY_EQ_TP_EXPIRY', 'OD_EXPIRY_GT_TP_EXPIRY', 'OD_EXPIRY_LT_TP_EXPIRY', 'OD_EXPIRY_DIFF_TP_EXPIRY_EQ_THREE', 'STANDALONE_OD', 'STANDALONE_TP','OD_EXPIRY_DIFF_TP_EXPIRY_EQ_FIVE','OD_EXPIRY_DIFF_TP_EXPIRY_EQ_ONE','OD_EXPIRY_DIFF_TP_EXPIRY_GT_ONE')")
    op.execute((
        "ALTER TABLE new_vehicle_cover ALTER COLUMN od_tp_condition TYPE ODTPConditions USING "
    ))
    op.execute("DROP TYPE ODTPConditions")
    op.execute("CREATE TYPE CurrentDateConditions AS ENUM('CURRENT_DATE_EQ_TP_EXPIRY', 'CURRENT_DATE_GT_TP_EXPIRY', 'CURRENT_DATE_LT_TP_EXPIRY', 'CURRENT_DATE_EQ_OD_EXPIRY', 'CURRENT_DATE_GT_OD_EXPIRY', 'CURRENT_DATE_LT_OD_EXPIRY')")
    op.execute((
        "ALTER TABLE new_vehicle_cover ALTER COLUMN current_date_conditions TYPE CurrentDateConditions USING "
    ))
    op.execute("DROP TYPE CurrentDateConditions")
    # ### end Alembic commands ###
