"""added_insurer_uin_column_in_vehicle_cover

Revision ID: 9a7fa8dea019
Revises: 4f410e15dc82
Create Date: 2023-02-13 18:37:21.576881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7fa8dea019'
down_revision = '4f410e15dc82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_cover', sa.Column('insurer_code', sa.VARCHAR(), nullable=True))
    op.add_column('vehicle_cover', sa.Column('uin', sa.VARCHAR(), nullable=True))
    op.create_unique_constraint(None, 'vehicle_cover', ['uin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_cover', type_='unique')
    op.drop_column('vehicle_cover', 'uin')
    op.drop_column('vehicle_cover', 'insurer_code')
    # ### end Alembic commands ###
