"""added in new table icvehiclecover mapping and prev_policy_vehicle_cover_mapping

Revision ID: ae2c051aeef2
Revises: 3e9026e380fd
Create Date: 2023-02-28 16:22:46.452649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2c051aeef2'
down_revision = '3e9026e380fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurer_vehicle_cover_mapping',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('insurer_code', sa.VARCHAR(), nullable=True),
    sa.Column('uin', sa.VARCHAR(), nullable=True),
    sa.Column('vehicle_cover_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_cover_id'], ['vehicle_cover.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uin')
    )
    op.create_table('policy_type_vehicle_cover_mapping',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_class_id', sa.Integer(), nullable=True),
    sa.Column('policy_type_id', sa.Integer(), nullable=True),
    sa.Column('prev_policy_type_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_cover_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['policy_type_id'], ['policy_type.id'], ),
    sa.ForeignKeyConstraint(['prev_policy_type_id'], ['previous_policy_type.id'], ),
    sa.ForeignKeyConstraint(['vehicle_class_id'], ['vehicle_class.id'], ),
    sa.ForeignKeyConstraint(['vehicle_cover_id'], ['vehicle_cover.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('vehicle_cover_uin_key', 'vehicle_cover', type_='unique')
    op.drop_constraint('vehicle_cover_vehicle_type_id_fkey', 'vehicle_cover', type_='foreignkey')
    op.drop_constraint('vehicle_cover_policy_type_id_fkey', 'vehicle_cover', type_='foreignkey')
    op.drop_constraint('vehicle_cover_vehicle_class_id_fkey', 'vehicle_cover', type_='foreignkey')
    op.drop_column('vehicle_cover', 'insurer_code')
    op.drop_column('vehicle_cover', 'vehicle_type_id')
    op.drop_column('vehicle_cover', 'full_name')
    op.drop_column('vehicle_cover', 'policy_type_id')
    op.drop_column('vehicle_cover', 'uin')
    op.drop_column('vehicle_cover', 'vehicle_class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_cover', sa.Column('vehicle_class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicle_cover', sa.Column('uin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle_cover', sa.Column('policy_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicle_cover', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle_cover', sa.Column('vehicle_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicle_cover', sa.Column('insurer_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('vehicle_cover_vehicle_class_id_fkey', 'vehicle_cover', 'vehicle_class', ['vehicle_class_id'], ['id'])
    op.create_foreign_key('vehicle_cover_policy_type_id_fkey', 'vehicle_cover', 'policy_type', ['policy_type_id'], ['id'])
    op.create_foreign_key('vehicle_cover_vehicle_type_id_fkey', 'vehicle_cover', 'vehicle_type', ['vehicle_type_id'], ['id'])
    op.create_unique_constraint('vehicle_cover_uin_key', 'vehicle_cover', ['uin'])
    op.drop_table('policy_type_vehicle_cover_mapping')
    op.drop_table('insurer_vehicle_cover_mapping')
    # ### end Alembic commands ###
