"""insurer renewal flag added

Revision ID: b6cb4137c77d
Revises: ca5832e02632
Create Date: 2023-03-09 15:59:47.440635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6cb4137c77d'
down_revision = 'ca5832e02632'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurer', sa.Column('is_renewal_integrated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurer', 'is_renewal_integrated')
    # ### end Alembic commands ###
