"""NCB-Type selection added

Revision ID: c4d49f0997e7
Revises: 13d5e09d61d4
Create Date: 2023-05-04 11:41:05.509668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d49f0997e7'
down_revision = '13d5e09d61d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('no_claim_bonus', sa.Column('allowed_previous_policy', sa.Boolean(), nullable=True))
    op.add_column('no_claim_bonus', sa.Column('allowed_reserving_letter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('no_claim_bonus', 'allowed_reserving_letter')
    op.drop_column('no_claim_bonus', 'allowed_previous_policy')
    # ### end Alembic commands ###
