"""table name change for dealer person

Revision ID: c7b1dadf0273
Revises: 9a7fa8dea019
Create Date: 2023-02-14 18:31:49.436449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7b1dadf0273'
down_revision = '9a7fa8dea019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designated_person',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designated_person_name', sa.VARCHAR(), nullable=False),
    sa.Column('oem_id', sa.Integer(), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['oem_id'], ['oem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('sales_manager_dealer_person_id_fkey', 'sales_manager', type_='foreignkey')
    op.drop_table('dealer_person')
    op.add_column('sales_manager', sa.Column('designated_person_id', sa.Integer(), nullable=True))
    op.create_foreign_key('sales_manager_designated_person_fkey', 'sales_manager', 'designated_person', ['designated_person_id'], ['id'])
    op.drop_column('sales_manager', 'dealer_person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_person',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dealer_person_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('oem_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name='dealer_person_dealer_id_fkey'),
    sa.ForeignKeyConstraint(['oem_id'], ['oem.id'], name='dealer_person_oem_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dealer_person_pkey')
    )
    op.add_column('sales_manager', sa.Column('dealer_person_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('sales_manager_designated_person_fkey', 'sales_manager', type_='foreignkey')
    op.create_foreign_key('sales_manager_dealer_person_id_fkey', 'sales_manager', 'dealer_person', ['dealer_person_id'], ['id'])
    op.drop_column('sales_manager', 'designated_person_id')
    op.drop_table('designated_person')
    # ### end Alembic commands ###
