"""dealer model updated

Revision ID: c9ad7416bb5f
Revises: 19217d48e99c
Create Date: 2023-01-31 15:24:36.874045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ad7416bb5f'
down_revision = '19217d48e99c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_beneficiary_details',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('pan_no', sa.VARCHAR(), nullable=True),
    sa.Column('aadhaar_no', sa.VARCHAR(), nullable=True),
    sa.Column('bank_account_no', sa.VARCHAR(), nullable=True),
    sa.Column('account_type', sa.VARCHAR(), nullable=True),
    sa.Column('ifsc_code', sa.VARCHAR(), nullable=True),
    sa.Column('micr_no', sa.VARCHAR(), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(), nullable=True),
    sa.Column('bank_branch', sa.VARCHAR(), nullable=True),
    sa.Column('bank_address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_detail',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.Integer(), nullable=True),
    sa.Column('vehicle_class', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['vehicle_class'], ['vehicle_class.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type'], ['vehicle_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adviser_name', sa.VARCHAR(), nullable=False),
    sa.Column('adviser_mobile_no', sa.VARCHAR(), nullable=False),
    sa.Column('adviser_email', sa.VARCHAR(), nullable=False),
    sa.Column('address_line_1', sa.VARCHAR(), nullable=False),
    sa.Column('address_line_2', sa.VARCHAR(), nullable=True),
    sa.Column('address_line_3', sa.VARCHAR(), nullable=True),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dealer', sa.Column('group_name', sa.VARCHAR(), nullable=True))
    op.add_column('dealer', sa.Column('dealer_principle_name', sa.VARCHAR(), nullable=False))
    op.add_column('dealer', sa.Column('address_line_1', sa.VARCHAR(), nullable=False))
    op.add_column('dealer', sa.Column('address_line_2', sa.VARCHAR(), nullable=True))
    op.add_column('dealer', sa.Column('address_line_3', sa.VARCHAR(), nullable=True))
    op.add_column('dealer', sa.Column('email', sa.VARCHAR(), nullable=False))
    op.add_column('dealer', sa.Column('mobile_no', sa.VARCHAR(), nullable=False))
    op.add_column('dealer', sa.Column('landline_no', sa.VARCHAR(), nullable=True))
    op.add_column('dealer', sa.Column('pincode_id', sa.Integer(), nullable=True))
    op.add_column('dealer', sa.Column('region_id', sa.Integer(), nullable=True))
    op.add_column('dealer', sa.Column('dealer_zone', sa.Integer(), nullable=True))
    op.add_column('dealer', sa.Column('pan_no', sa.VARCHAR(), nullable=False))
    op.add_column('dealer', sa.Column('gstin', sa.VARCHAR(), nullable=True))
    op.add_column('dealer', sa.Column('misp_code', sa.VARCHAR(), nullable=True))
    op.add_column('dealer', sa.Column('dealer_category', sa.VARCHAR(), nullable=True))
    op.add_column('dealer', sa.Column('broker_zone', sa.Integer(), nullable=True))
    op.add_column('dealer', sa.Column('oem_zone', sa.Integer(), nullable=True))
    op.add_column('dealer', sa.Column('relationship_manager', sa.VARCHAR(), nullable=True))
    op.add_column('dealer', sa.Column('designated_person', sa.VARCHAR(), nullable=True))
    op.create_foreign_key("fk_dealer_id_broker_zone", 'dealer', 'rto_zone', ['broker_zone'], ['id'])
    op.create_foreign_key("fk_dealer_id_oem_zone", 'dealer', 'rto_zone', ['oem_zone'], ['id'])
    op.create_foreign_key("fk_dealer_id_region_id", 'dealer', 'region', ['region_id'], ['id'])
    op.create_foreign_key("fk_dealer_id_dealer_zone", 'dealer', 'rto_zone', ['dealer_zone'], ['id'])
    op.create_foreign_key("fk_dealer_id_pincode_id", 'dealer', 'pincode', ['pincode_id'], ['id'])
    op.add_column('vehicle_class', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('vehicle_class', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_class', 'modified_at')
    op.drop_column('vehicle_class', 'created_at')
    op.drop_constraint("fk_dealer_id_broker_zone", 'dealer', type_='foreignkey')
    op.drop_constraint("fk_dealer_id_oem_zone", 'dealer', type_='foreignkey')
    op.drop_constraint("fk_dealer_id_region_id", 'dealer', type_='foreignkey')
    op.drop_constraint("fk_dealer_id_dealer_zone", 'dealer', type_='foreignkey')
    op.drop_constraint("fk_dealer_id_pincode_id", 'dealer', type_='foreignkey')
    op.drop_column('dealer', 'designated_person')
    op.drop_column('dealer', 'relationship_manager')
    op.drop_column('dealer', 'oem_zone')
    op.drop_column('dealer', 'broker_zone')
    op.drop_column('dealer', 'dealer_category')
    op.drop_column('dealer', 'misp_code')
    op.drop_column('dealer', 'gstin')
    op.drop_column('dealer', 'pan_no')
    op.drop_column('dealer', 'dealer_zone')
    op.drop_column('dealer', 'region_id')
    op.drop_column('dealer', 'pincode_id')
    op.drop_column('dealer', 'landline_no')
    op.drop_column('dealer', 'mobile_no')
    op.drop_column('dealer', 'email')
    op.drop_column('dealer', 'address_line_3')
    op.drop_column('dealer', 'address_line_2')
    op.drop_column('dealer', 'address_line_1')
    op.drop_column('dealer', 'dealer_principle_name')
    op.drop_column('dealer', 'group_name')
    op.drop_table('workshop')
    op.drop_table('business_detail')
    op.drop_table('workshop_beneficiary_details')
    # ### end Alembic commands ###
