"""added renewal vehicle cover

Revision ID: ca5832e02632
Revises: ae2c051aeef2
Create Date: 2023-03-07 14:32:40.885679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5832e02632'
down_revision = 'ae2c051aeef2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE ODTPConditions ADD VALUE 'OD_EXPIRY_DIFF_TP_EXPIRY_EQ_FIVE'")
        op.execute("ALTER TYPE ODTPConditions ADD VALUE 'OD_EXPIRY_DIFF_TP_EXPIRY_EQ_ONE'")
        op.execute("ALTER TYPE ODTPConditions ADD VALUE 'OD_EXPIRY_DIFF_TP_EXPIRY_GT_ONE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE ODTPConditions AS ENUM('OD_EXPIRY_EQ_TP_EXPIRY', 'OD_EXPIRY_GT_TP_EXPIRY', 'OD_EXPIRY_LT_TP_EXPIRY', 'OD_EXPIRY_DIFF_TP_EXPIRY_EQ_THREE', 'STANDALONE_OD', 'STANDALONE_TP')")
    op.execute((
        "ALTER TABLE new_vehicle_cover ALTER COLUMN od_tp_condition TYPE ODTPConditions USING "
    ))
    op.execute("DROP TYPE ODTPConditions")
    # ### end Alembic commands ###
