"""change renewal vehicle cover

Revision ID: f2b0d82fc60a
Revises: 266cdb7fb862
Create Date: 2023-03-16 17:25:38.176900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b0d82fc60a'
down_revision = '266cdb7fb862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_vehicle_cover', sa.Column('policy_type_vehicle_cover_mapping_id', sa.Integer(), nullable=True))
    op.drop_constraint('new_vehicle_cover_vehicle_cover_id_fkey', 'new_vehicle_cover', type_='foreignkey')
    op.drop_constraint('new_vehicle_cover_old_vehicle_cover_id_fkey', 'new_vehicle_cover', type_='foreignkey')
    op.create_foreign_key("new_vehicle_cover_policy_type_fkey", 'new_vehicle_cover', 'policy_type_vehicle_cover_mapping', ['old_vehicle_cover_id'], ['id'])
    op.create_foreign_key("new_vehicle_cover_policy_type__vehicle_fkey", 'new_vehicle_cover', 'policy_type_vehicle_cover_mapping', ['policy_type_vehicle_cover_mapping_id'], ['id'])
    op.drop_column('new_vehicle_cover', 'vehicle_cover_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_vehicle_cover', sa.Column('vehicle_cover_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint("new_vehicle_cover_policy_type_fkey", 'new_vehicle_cover', type_='foreignkey')
    op.drop_constraint("new_vehicle_cover_policy_type__vehicle_fkey", 'new_vehicle_cover', type_='foreignkey')
    op.create_foreign_key('new_vehicle_cover_old_vehicle_cover_id_fkey', 'new_vehicle_cover', 'vehicle_cover', ['old_vehicle_cover_id'], ['id'])
    op.create_foreign_key('new_vehicle_cover_vehicle_cover_id_fkey', 'new_vehicle_cover', 'vehicle_cover', ['vehicle_cover_id'], ['id'])
    op.drop_column('new_vehicle_cover', 'policy_type_vehicle_cover_mapping_id')
    # ### end Alembic commands ###
