"""naming fix and max amount added

Revision ID: 61d22f97f486
Revises: b04ecd0a7c18
Create Date: 2022-12-28 12:37:01.574724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61d22f97f486'
down_revision = 'b04ecd0a7c18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voluntary_deductible',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_type', sa.Integer(), nullable=True),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('deductible', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('max_discount', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_till', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('deductible')
    op.add_column('cover_rate', sa.Column('code', sa.VARCHAR(), nullable=False))
    op.add_column('cover_rate', sa.Column('max_amount', sa.Integer(), nullable=False))
    op.add_column('cover_rate', sa.Column('cover_percent', sa.Float(), nullable=False))
    op.drop_column('cover_rate', 'amount')
    op.add_column('pa_rate', sa.Column('cover_code', sa.VARCHAR(), nullable=True))
    op.drop_column('pa_rate', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pa_rate', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pa_rate', 'cover_code')
    op.add_column('cover_rate', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cover_rate', 'cover_percent')
    op.drop_column('cover_rate', 'max_amount')
    op.drop_column('cover_rate', 'code')
    op.create_table('deductible',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deductible', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discount_percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_discount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('valid_till', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='deductible_pkey')
    )
    op.drop_table('voluntary_deductible')
    # ### end Alembic commands ###
