"""added fuel_type in OD_rate

Revision ID: 7b8848b1301a
Revises: d4f0ab12a7b6
Create Date: 2023-01-16 15:25:20.500442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8848b1301a'
down_revision = 'd4f0ab12a7b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('od_rate', sa.Column('fuel_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('od_rate', 'fuel_type')
    # ### end Alembic commands ###
