"""inital tables added.

Revision ID: b04ecd0a7c18
Revises: 
Create Date: 2022-08-05 01:01:19.316324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04ecd0a7c18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addon_bundle_price',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addon_bundle_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('insurer_code', sa.VARCHAR(), nullable=True),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('is_ncb', sa.Boolean(), nullable=True),
    sa.Column('add_on_prev_policy', sa.Boolean(), nullable=True),
    sa.Column('vehicle_min_age', sa.Integer(), nullable=True),
    sa.Column('vehicle_max_age', sa.Integer(), nullable=True),
    sa.Column('min_cc', sa.Integer(), nullable=True),
    sa.Column('max_cc', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_till', sa.TIMESTAMP(), nullable=True),
    sa.Column('bundle_premium', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addon_price',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=True),
    sa.Column('insurer_code', sa.VARCHAR(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('is_ncb', sa.Boolean(), nullable=True),
    sa.Column('add_on_prev_policy', sa.Boolean(), nullable=True),
    sa.Column('vehicle_min_age', sa.Integer(), nullable=True),
    sa.Column('vehicle_max_age', sa.Integer(), nullable=True),
    sa.Column('min_cc', sa.Integer(), nullable=True),
    sa.Column('max_cc', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_till', sa.TIMESTAMP(), nullable=True),
    sa.Column('addon_premium', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cover_rate',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_till', sa.TIMESTAMP(), nullable=True),
    sa.Column('cover_type', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deductible',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_type', sa.Integer(), nullable=True),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('deductible', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('max_discount', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_till', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depreciation',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('min_vehicle_age', sa.Integer(), nullable=True),
    sa.Column('max_vehicle_age', sa.Integer(), nullable=True),
    sa.Column('depreciation_rate', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_till', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('city_cluster', sa.Integer(), nullable=True),
    sa.Column('rto_code', sa.Integer(), nullable=True),
    sa.Column('rto_cluster', sa.Integer(), nullable=True),
    sa.Column('business_type', sa.Integer(), nullable=True),
    sa.Column('dealer_code', sa.VARCHAR(), nullable=True),
    sa.Column('vin_no', sa.VARCHAR(), nullable=True),
    sa.Column('insurer_code', sa.VARCHAR(), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.Column('renewal_type', sa.VARCHAR(), nullable=True),
    sa.Column('model_id', sa.VARCHAR(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('min_ncb', sa.Integer(), nullable=True),
    sa.Column('max_ncb', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.Integer(), nullable=True),
    sa.Column('vehicle_min_age', sa.Integer(), nullable=True),
    sa.Column('vehicle_max_age', sa.Integer(), nullable=True),
    sa.Column('min_cc', sa.Integer(), nullable=True),
    sa.Column('max_cc', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_till', sa.TIMESTAMP(), nullable=True),
    sa.Column('discount_precent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ncb',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_type', sa.Integer(), nullable=True),
    sa.Column('prev_policy_type', sa.Integer(), nullable=True),
    sa.Column('is_claimed_last_year', sa.Boolean(), nullable=True),
    sa.Column('last_year_ncb', sa.Integer(), nullable=True),
    sa.Column('claim_count', sa.Integer(), nullable=True),
    sa.Column('applicable_ncb', sa.Integer(), nullable=True),
    sa.Column('insurer_code', sa.VARCHAR(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_till', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('od_rate',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_type', sa.Integer(), nullable=True),
    sa.Column('min_vehicle_age', sa.Integer(), nullable=True),
    sa.Column('max_vehicle_age', sa.Integer(), nullable=True),
    sa.Column('rto_zone', sa.Integer(), nullable=True),
    sa.Column('min_cc', sa.Integer(), nullable=True),
    sa.Column('max_cc', sa.Integer(), nullable=True),
    sa.Column('od_term', sa.Integer(), nullable=True),
    sa.Column('rate_percent', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_till', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pa_rate',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_type', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('tp_tenure', sa.Integer(), nullable=True),
    sa.Column('per_10k_rate', sa.Float(), nullable=True),
    sa.Column('insurer_code', sa.VARCHAR(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_till', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tp_rate',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_type', sa.Integer(), nullable=True),
    sa.Column('vehicle_category', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.Integer(), nullable=True),
    sa.Column('min_cc', sa.Integer(), nullable=True),
    sa.Column('max_cc', sa.Integer(), nullable=True),
    sa.Column('tp_term', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_till', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tp_rate')
    op.drop_table('pa_rate')
    op.drop_table('od_rate')
    op.drop_table('ncb')
    op.drop_table('discount')
    op.drop_table('depreciation')
    op.drop_table('deductible')
    op.drop_table('cover_rate')
    op.drop_table('addon_price')
    op.drop_table('addon_bundle_price')
    # ### end Alembic commands ###
