"""Added tables for documentic

Revision ID: 06f85f9f39a6
Revises: 
Create Date: 2022-08-09 16:53:20.259967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f85f9f39a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentstatus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), nullable=False),
    sa.Column('current_state', sa.Enum('REQUEST_RECEIVED', 'VALIDATION_ERROR', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='policypdfstatus'), nullable=False),
    sa.Column('policy_uuid', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), nullable=False),
    sa.Column('html', sa.VARCHAR(), nullable=True),
    sa.Column('insurer_code', sa.VARCHAR(), nullable=True),
    sa.Column('doctype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctype_id'], ['doctype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    op.drop_table('documentstatus')
    op.drop_table('doctype')
    # ### end Alembic commands ###
