"""changed column name from updated at to modified at

Revision ID: 23dd29e98b1e
Revises: ddf8d16e53e3
Create Date: 2022-10-11 18:05:17.530763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23dd29e98b1e'
down_revision = 'ddf8d16e53e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentstatus', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.drop_column('documentstatus', 'updated_at')
    op.add_column('templates', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.drop_column('templates', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('templates', 'modified_at')
    op.add_column('documentstatus', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('documentstatus', 'modified_at')
    # ### end Alembic commands ###
