"""alter datetime from epoch to datetime

Revision ID: ddf8d16e53e3
Revises: 1a5e9cf78326
Create Date: 2022-09-14 17:06:31.164353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf8d16e53e3'
down_revision = '1a5e9cf78326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentstatus', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documentstatus', 'updated_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('templates', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('templates', 'updated_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'updated_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('templates', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documentstatus', 'updated_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documentstatus', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
