from app.models.addons import *
from app.models.coverage_details import *
from app.models.financier import *
from app.models.insurer import *
from app.models.location import *
from app.models.personal_details import *
from app.models.policy_details import *
from app.models.vehicle_details import *
from app.models.admin_details import *
from rb_utils.database.sql.sql_base import SqlDB